[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health/debug"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[deploy.variables]
ENVIRONMENT = "production" 