apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus_dev:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres_dev:5432
    database: healthmate_dev
    user: healthmate_dev_user
    isDefault: false
    editable: true
    jsonData:
      sslmode: "disable"
      maxOpenConns: 50
      maxIdleConns: 50
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: "dev_password"

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis_dev:6379
    isDefault: false
    editable: true
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData: {} 