[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc", "curl"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements-railway.txt"
]

[start]
cmd = "chmod +x start.sh && ./start.sh" 